version: "3.8"
services:
  vote:
    build: ./vote
    ports:
      - "5000:80"
    networks:
      - backend
    depends_on:
      - redis
  
  redis:
    image: "redis:alpine"
    networks:
      - backend
  
  worker:
    build: ./worker
    networks:
      - backend
    depends_on:
      - redis
      - db
  
  db:
    image: "postgres:13-alpine"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - backend
    volumes:
      - db-data:/var/lib/postgresql/data
  
  result:
    build: ./result
    ports:
      - "5001:80"
    networks:
      - backend
    depends_on:
      - db
  
networks:
  backend:

volumes:
  db-data: